apps/home/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from apps.home.views import IndexView,LoginView,SignupView,LogoutView
app_name = 'home'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^logout', LogoutView.as_view(), name='logout'),
    url(r'^signup', SignupView.as_view(), name='signup'),
]

apps/reports/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from apps.reports.views import IndexView
app_name = 'reports'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

kiffert/urls.py
from django.conf.urls import url, include, static
from django.urls import include,path
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls',namespace='home')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^report-settings/', include('apps.report_settings.urls',namespace='report-settings'))
]

apps/reports/models.py
from django.db import models

# Create your models here.

apps/reports/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
import mws
from kiffert import settings
from django.views.generic import TemplateView, FormView, View, ListView
# Create your views here.
from apps.home.decorators import check_user_auth

@method_decorator(check_user_auth, name='dispatch')
class IndexView(TemplateView):
	template_name = 'reports/index.html'
	def get(self,request):
		order_api = mws.Orders(
			access_key=settings.MWS_ACCESS_KEY,
			secret_key=settings.MWS_SECRET_KEY,
			account_id=settings.MWS_ACCOUNT_ID,
			region='IN',
			)
		service_status = order_api.get_service_status()
		print(service_status.parsed)
		context = {'email': self.request.session['email']}
		return render(self.request,"reports/index.html",context)

templates/reports/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/report.css' %}">
{% endblock %}
{% block title %}Reports{% endblock %}

{% block header_menu %}
    <li class="dropdown"><a href="">Account</a></li>
    <div class="dropdown-box">
        <div class="dropdown-top">
            <span></span>
        </div>
        <div class="dropdown-content">
            <ul>
                <li><a>{{email}}</a></li>
                <li><a href="{% url 'account:index' %}">Account Settings</a></li>
                <li><a href="{% url 'home:logout' %}">Logout</a></li>
                <hr>
                <li><a href='#'>Support</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}

<div class="report-btn">
    <img src="{% static 'img/report.png'%}" />
    <p>All reports</p>
</div>

<div class="report-div">
    <p class="main-title">Reports</p>
    <div>
        <p class="sub-title">Category</p>
        <div class="sub-content">
            <p> &#9900;   Report</p>
            <p> &#9900;   Report</p>
        </div>
    </div>
    <img class="report-setting" src="{% static 'img/setting.png'%}" />
    <img class="report-close" src="{% static 'img/close.png'%}" />
</div>

<div class="filter-btn">
    <img src="{% static 'img/filter.png'%}" />
    <p>Filters</p>
</div>

<div class="filter-div">
    <p class="main-title">Filters</p>
    <div>
        <p class="sub-title">Category</p>
        <div class="sub-content">
            <p> &#9900;   Criteria</p>
            <p> &#9900;   Criteria</p>
        </div>
    </div>
    <img class="filter-close" src="{% static 'img/close.png'%}" />
</div>

{% endblock content %}

{% block script %}
<script>
    $(document).ready(function(){
        $(".report-btn").click(function(){
            $(".report-div").show();
        })
        $(".report-setting").click(function(){
            location.href = "{% url 'report-settings:index' %}";
        })
        $(".report-close").click(function(){
            $(".report-div").hide();
        })

        $(".filter-btn").click(function(){
            $(".filter-div").show();
        })
        $(".filter-close").click(function(){
            $(".filter-div").hide();
        })
    });
</script>
{% endblock script %}

templates/reports/setting.html
{% extends 'base.html' %} 
{% load static %} 
{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/report.css' %}">
{% endblock %}
{% block title %}Reports{% endblock %}

{% block header_menu %}
    <li><a href="{% url 'reports:index' %}">Reports</a></li>
    <li class="dropdown"><a href="">Account</a></li>
    <div class="dropdown-box">
        <div class="dropdown-top">
            <span></span>
        </div>
        <div class="dropdown-content">
            <ul>
                <li><a>{{email}}</a></li>
                <li><a href="{% url 'account:index' %}">Account Settings</a></li>
                <li><a href="{% url 'home:logout' %}">Logout</a></li>
                <hr>
                <li><a href='#'>Support</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}

<div class="report-setting-div">
    <p class="main-title">Data Sources</p>
    <div>
        <p class="sub-title">Store Name</p>
        <div class="sub-content">
            <p> &#9900;   API</p>
            <p> &#9900;   File Upload</p>
        </div>
    </div>
</div>

<div class="filter-btn">
    <img src="{% static 'img/filter.png'%}" />
    <p>Filters</p>
</div>

<div class="filter-div">
    <p class="main-title">Filters</p>
    <div>
        <p class="sub-title">Category</p>
        <div class="sub-content">
            <p> &#9900;   Criteria</p>
            <p> &#9900;   Criteria</p>
        </div>
    </div>
    <img class="filter-close" src="{% static 'img/close.png'%}" />
</div>

{% endblock content %}

{% block script %}
<script>
    $(document).ready(function(){

        $(".filter-btn").click(function(){
            $(".filter-div").show();
        })
        $(".filter-close").click(function(){
            $(".filter-div").hide();
        })
    });
</script>
{% endblock script %}