apps/home/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from apps.home.views import IndexView,LoginView,SignupView,LogoutView
app_name = 'home'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^logout', LogoutView.as_view(), name='logout'),
    url(r'^signup', SignupView.as_view(), name='signup'),
]

kiffert/urls.py
from django.conf.urls import url, include, static
from django.urls import include,path
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls',namespace='home')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^report-settings/', include('apps.report_settings.urls',namespace='report-settings'))
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>KIFFERT | {% block title %}Home{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/util.css' %}">
    {% block extra_styles %}{% endblock %}

    <!--scripts-->
</head>
<body>

{% block header %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home:index' %}"><h1>KIFFERT</h1> </a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>            
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
            {% block header_menu %}
                <li><a href="">About</a></li>
                <li><a href="{% url 'home:signup' %}">Signup</a></li>
                <li><a href="{% url 'home:login' %}">Login</a></li>
            {% endblock %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<section class="home-content">
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
</section>
{% endblock %}
{% block jsfile %}
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>


<!-- extra js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
<script src="{% static 'js/intlTelInput.js' %}"></script>

{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
    });
</script>
{% endblock %}
</body>
</html>